### ISSUE TITLE
Select Colours on Pie charts

### ISSUE THREAD

**Issue by mfcRogue** [LaravelDaily/laravel-charts#6]
Is there away to customise / select specific colours for Pie Charts, currently it changes each time it is refreshed.

**Comment by PovilasKorop** [comment]
@mfcRogue currently not, because the grouping categories are dynamic, so the package doesn't know upfront what are your categories. But maybe we can add it as parameters so you would pass an optional array of colors per category, would that be ok for you?

Maybe you could even try to implement it yourself and submit a Pull Request? Cause I'm not sure when exactly we would be able to implement this feature, currently have other priorities.

**Comment by mfcRogue** [comment]
I've just hard coded it for now, since my group will always have a set amount.

Colour can be found in > vendor\laraveldaily\laravel-charts\src\views\javascript.blade.php

Should be able to run normal eloquent commands in the blade so if needed anyone could create a colour field in the DB to match colours if required.

**Comment by PovilasKorop** [comment]
@mfcRogue thanks for the follow up comment. Launching eloquent queries from blade is a bad practice, so those colors should come from some config file. We will consider it in the future.
